### PR TITLE
Issue33

### PR DESCRIPTION
**Pull request by p4p4j0hn**
## Problem

- Fix issue 33. Data dir not backed up on pre-upgrade backup. When trying my upgrade to v0.58.4 branch, I discovered that the data directory isn't backed up with the app. Since this version upgrade includes a database change it breaks backward compatibility.

## Solution

- Removed the optional backup flags from the scripts.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by p4p4j0hn** [comment]
!testme

**Comment by ericgaspar** [comment]
!ttestme

**Comment by ericgaspar** [comment]
!testme

**Comment by p4p4j0hn** [comment]
@ericgaspar Can this be merged?

**Comment by alexAubin** [comment]
Hmmm this sounds the exact situation described in https://github.com/YunoHost/yunohost/pull/1443

But I don't have my neurons properly connected right now to each other to think about if / what is the right way to address this x_x

But it's pretty spooky :|

**Comment by p4p4j0hn** [comment]
This might just be a non issue... It is only a problem if the upgrade goes wrong. As long as the upgrade is tested and proven to work, we don't need to add this tweak to the package.

**Comment by p4p4j0hn** [comment]
> Hmmm this sounds the exact situation described in YunoHost/yunohost#1443
> 
> But I don't have my neurons properly connected right now to each other to think about if / what is the right way to address this x_x
> 
> But it's pretty spooky :|

This is not like that issue. The next version upgrade includes a database schema change, if the upgrade fails, there is no way to restore the preupgrade backup because the new database in the datadir is not compatible with the previous version. So for the next upgrade we should include the datadir in the pre-upgrade backup.

**Pull request closed without merging**
