### PR TITLE
fix linter

### PR DESCRIPTION
**Pull request by ericgaspar**
- Fix linter
- systemd hardening

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by ericgaspar** [comment]
I think the CI dev is broken... testing with another CI

**Comment by ericgaspar** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Pull request closed without merging**
